######################################################
#
# splunk_app_addon-builder
#
# Copyright (C) 2005-2016 Splunk Inc. All Rights Reserved.
#
######################################################

[install]
is_configured = false
state = enabled
build = 0
install_source_checksum = d95dfe931be12090db4bb81a346e4a587fd0311a

[ui]
is_visible = true
label = Splunk Add-on Builder
docs_section_override = AddOns:released

[launcher]
author = Splunk
version = 4.1.3
description = Splunk Add-on Builder

[package]
id = splunk_app_addon-builder

[triggers]
reload.field_extraction_token = simple
reload.field_extraction_field = simple
reload.field_validator = simple
reload.aob_eval_functions = simple
reload.field_extraction_kv_templates = simple
reload.ui-metrics-collector = simple
reload.settings = simple
